# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

# There are lots of internals of Shake want to test, but don't want to expose
- message: Module reused between components

# There are a few general modules that offer a complete interface,
# but only a subset is used by Shake
- message:
  - name: Weeds exported
  - module: [General.Bilist, General.Ids, General.Intern, General.TypeMap, General.EscCodes, General.ListBuilder]

# These packages are used on older compilers for compatibility methods
- message:
  - name: Redundant build-depends entry
  - depends: [old-time, semigroups]
